name: UNIT-TESTS

on:
  push:
    branches: [ feature/autoBuildParser ]
    
  pull_request:
    branches: [ feature/autoBuildParser ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make test
      run: make test
