name: UNIT-TESTS

on:
  push:
    branches: [ AlpiScript ]
  pull_request:
    branches: [ AlpiScript ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install java
    - uses: actions/setup-java@v2
      with:
       distribution: 'temurin'
       java-version: '11'
    - uses: actions/checkout@v2
    - name: buildParser
      run: buildParser.sh
    - name: make
      run: make
    - name: make test
      run: make test
