name: C/C++ CI

on:
  push:
    branches: [ AlpiScript ]
  pull_request:
    branches: [ AlpiScript ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      run: buildParser.sh
    - name: make
      run: make
    - name: make test
      run: make test
      name: C/C++ CI
      
